[package]
name = "btce-trollbox"
version = "0.1.0"
authors = ["Viacheslav Ivanov <vyacheslav.ivanov@evoplus.ca>"]


[dependencies]
rustc-serialize = "0.3.21"
term = "0.4.4"
regex = "0.1.80"
websocket = "0.17.1"
hyper = "0.9.12"
time = "0.1.35"
docopt = "0.6.86"
